stages:
  - deploy

deploy-backend:
  image: docker:latest
  stage: deploy
  tags:
    - production
  before_script:
    - apk add --no-cache docker-compose
  script:
    - export SERVER_URL=$CI_SERVER_URL
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build --force-recreate
  only:
    refs:
      - deploy-production
  except:
    changes:
      - terraform/*