version: "3.7"

services:
    broker:
        image: eclipse-mosquitto
        networks:
            - node-red-net
        ports:
            - "1883:1883"
    node-red:
        image: nodered/node-red:latest
        environment:
        - TZ=Europe/London
        ports:
        - "1880:1880"
        networks:
        - node-red-net

volumes:
    node-red-data:

networks:
    node-red-net: