version: '3.7'

services:
  broker:
      ports:
          - "8883:8883"
      volumes:
          - "./production_config/mosquitto:/mosquitto"
          - /etc/letsencrypt/live/${SERVER_URL}:/etc/letsencrypt/live/${SERVER_URL}
          - /etc/letsencrypt/archive/${SERVER_URL}:/etc/letsencrypt/archive/${SERVER_URL}
  node-red:
      volumes:
          - ./production_config/node-red-data:/data